name: vmerge
description: A video merger app created by BBK Development.
version: 2.0.0+8
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  android_intent_plus: ^5.0.2
  bloc: ^8.1.4
  bottom_navy_bar:
    git:
      url: https://github.com/BBarisKilic/bottom_navy_bar.git
      ref: master
  collection: ^1.18.0
  equatable: ^2.0.5
  ffmpeg_service:
    path: packages/ffmpeg_service
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  image_gallery_saver: ^2.0.3
  in_app_review_service:
    git:
      url: https://github.com/BBKDevelopment/In-App-Review-Service.git
      ref: v1.0.1
  intl: 0.19.0
  modal_bottom_sheet: ^3.0.0
  objectbox: ^2.5.1
  objectbox_flutter_libs: ^2.5.1
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  url_launcher_service:
    git:
      url: https://github.com/BBKDevelopment/Url-Launcher-Service.git
      ref: v1.0.0
  video_player: ^2.8.7
  video_player_service:
    git:
      url: https://github.com/BBKDevelopment/Video-Player-Service.git
      ref: v1.2.1
  wakelock_service:
    git:
      url: https://github.com/BBKDevelopment/Wakelock-Service.git
      ref: v1.1.0
  wechat_assets_picker: ^9.1.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: ^2.5.1
  very_good_analysis: ^6.0.0

flutter_gen:
  output: lib/src/core/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

objectbox:
  output_dir: src/core/gen/

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/roboto_mono/
    - assets/images/
    - assets/licenses/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/roboto_mono/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto_mono/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/roboto_mono/RobotoMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto_mono/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_mono/RobotoMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_mono/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto_mono/RobotoMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_mono/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
