name: vmerge
description: A video merger app created by BBK Development.
version: 1.1.1+6
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bottom_navy_bar: ^6.0.0
  collection: ^1.17.2
  device_info_plus: ^9.1.1
  equatable: ^2.0.5
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.4
  flutter_svg: ^2.0.8
  get: ^4.6.6
  get_it: ^7.6.4
  go_router: ^13.0.1
  image_gallery_saver: ^2.0.3
  intl: ^0.18.0
  launch_review_service:
    git:
      url: https://github.com/BBKDevelopment/Launch-Review-Service.git
      ref: v1.0.0
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^4.2.0
  path: ^1.8.3
  path_provider: ^2.1.2
  url_launcher_service:
    git:
      url: https://github.com/BBKDevelopment/Url-Launcher-Service.git
      ref: v1.0.0
  video_player: ^2.8.1
  video_player_service:
    git:
      url: https://github.com/BBKDevelopment/Video-Player-Service.git
      ref: v1.0.0
  wechat_assets_picker: ^8.8.1+1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/src/core/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/roboto_mono/
    - assets/images/
    - assets/licenses/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/roboto_mono/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto_mono/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/roboto_mono/RobotoMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto_mono/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto_mono/RobotoMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_mono/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto_mono/RobotoMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/roboto_mono/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_mono/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
